name = "random-gift-roman"
main = "worker.js"
compatibility_date = "2024-09-30"

[[kv_namespaces]]
binding = "KV"
id = "255f4944a2db4bc897da1a259236fada"

[[d1_databases]]
binding = "DB"
database_name = "random_gift_db_v3"
database_id = "e2eb1ec1-5f76-4995-9a07-fc18a2fa9fd7"

[vars]
ALLOWED_ORIGIN = "https://torunok.github.io"

[[r2_buckets]]
binding = "R2"
bucket_name = "gift-images"

# Секрети додати окремо:
# wrangler secret put JWT_SECRET
# wrangler secret put ADMIN_USER
# wrangler secret put ADMIN_PASS
# wrangler secret put SALT
