name = "random-gift-roman"
main = "worker.js"
compatibility_date = "2024-09-30"

[[kv_namespaces]]
binding = "KV"
id = "__FILL_AFTER_CREATE__"

[[d1_databases]]
binding = "DB"
database_name = "random_gift_db"
database_id = "__FILL_AFTER_CREATE__"

[vars]
ALLOWED_ORIGIN = "https://YOUR_GITHUB_PAGES_DOMAIN" # напр.: https://romanmoloshiy.github.io

# Секрети додати окремо:
# wrangler secret put JWT_SECRET
# wrangler secret put ADMIN_USER
# wrangler secret put ADMIN_PASS
# wrangler secret put SALT