name = "random-gift-roman"
main = "worker.js"
compatibility_date = "2024-09-30"

[[kv_namespaces]]
binding = "KV"
id = "5ae998a2f15a4265bb0cf923d96ec16b"

[[d1_databases]]
binding = "random_gift_db_v2"
database_name = "random_gift_db_v2"
database_id = "371a7a79-24ed-48af-b3bb-74ed6225823c"


[vars]
ALLOWED_ORIGIN = "https://torunok.github.io" # напр.: https://romanmoloshiy.github.io

[[r2_buckets]]
binding = "R2"                 # так звертатимемось у коді: env.R2
bucket_name = "gift-images"    # створимо за хвилину командою

# Секрети додати окремо:
# wrangler secret put JWT_SECRET
# wrangler secret put ADMIN_USER
# wrangler secret put ADMIN_PASS
# wrangler secret put SALT
