name = "random-gift-roman"
main = "worker.js"
compatibility_date = "2024-09-30"

[[kv_namespaces]]
binding = "KV"
id = "86f8673bcbc749c789b796fc106c7108"

[[d1_databases]]
binding = "DB"
database_name = "random_gift_db_new"
database_id = "d22b8c06-a9cc-47f7-9e6f-3c5334689fe8"


[vars]
ALLOWED_ORIGIN = "https://torunok.github.io" # напр.: https://romanmoloshiy.github.io

[[r2_buckets]]
binding = "R2"                 # так звертатимемось у коді: env.R2
bucket_name = "gift-images"    # створимо за хвилину командою

# Секрети додати окремо:
# wrangler secret put JWT_SECRET
# wrangler secret put ADMIN_USER
# wrangler secret put ADMIN_PASS
# wrangler secret put SALT
