name = "random-gift-roman"
main = "worker.js"
compatibility_date = "2024-09-30"

[[kv_namespaces]]
binding = "KV"
id = "5ae998a2f15a4265bb0cf923d96ec16b"



[vars]
ALLOWED_ORIGIN = "https://torunok.github.io"

[[r2_buckets]]
binding = "R2"
bucket_name = "gift-images"

# Секрети додати окремо:
# wrangler secret put JWT_SECRET
# wrangler secret put ADMIN_USER
# wrangler secret put ADMIN_PASS
# wrangler secret put SALT
